version: "3.8"
services:
  movies:
    image: mykt/paymovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: mykt/paytrain:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  dth:
    image: mykt/paydth:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge:
    image: mykt/payrecharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
